version: "3"
services:
  nginx:
    ports:
      - "4000:80"
  node-project:
    build:
      context: . 
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=qht
      - MONGO_PASSWORD=mypass
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=qht
      - MONGO_INITDB_ROOT_PASSWORD=mypass